name: Build & Deploy from source.zip to GitHub Pages

on:
  push:
    paths:
      - 'source.zip'
      - '.github/workflows/pages-from-source-zip.yml'
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip source
        run: |
          mkdir srcpkg
          unzip -q source.zip -d srcpkg

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: srcpkg/package-lock.json

      - name: Install
        working-directory: srcpkg
        run: npm ci || npm install

      - name: Build & Export
        working-directory: srcpkg
        env:
          GH_PAGES_REPO: MegaForge   # Project Pages: https://souta192.github.io/MegaForge/
        run: |
          npm run build
          npx next export

      - name: Prepare static output
        run: |
          mkdir out
          rsync -a srcpkg/out/ out/ || rsync -a srcpkg/.next/export/ out/ || true
          [ -f out/index.html ] && cp out/index.html out/404.html || true
          touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
